name: dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
