name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        run: go test -v ./...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - name: Build
        run: go build -o email-service .

      - name: Upload build to S3
        run: aws s3 cp ./email-service s3://ruanscherer-email-service/

# Trying to deploy to EC2 for now. Intend to use ECS later...
#      - uses: docker/setup-qemu-action@v3
#      - uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./docker/Dockerfile
#          push: true
#          tags: ruanscherer/email-service:latest
